# Generated by Django 4.0.4 on 2023-03-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=1200)),
                ('Role', models.CharField(choices=[('Recruiter', 'Recruiter'), ('University', 'University')], default='College', max_length=20)),
            ],
        ),
    ]
